//
//  DemoFeed.swift
//  Venture
//
//  Created by Lawrence Liu on 1/11/24.
//

import SwiftUI

/*
 Feed aggregated variable for now. In future, this should be retrieved through backend
 */
//var posts : [PostModel] = profiles.flatMap { $0.posts }

var posts = [
    
    PostModel(
        title: "Our ASES Group in SF!",
        info: "7 photos",
        caption: "core memories, best friends forever.",
        media: ["861A6367", "Chinatown 1", "861A6368" , "Chinatown 3", "Fish", "Fish 2", "861A6374", "861A6375", "861A6384", "861A6371", "861A6419"],
        username: "kcheng05",
        profilePicture: "IMG_5155",
        numberOfComments: 2,
        friendsMutuals: [1, 2],
        itinerary: ItineraryModel(
            title: ["🤑 Overall Costs", "🚗 Booking Zip Car", "📍 Basa Seafood Express in Mission District", "📍 Catching Sunset @ Twin Peaks", "📍 Bingsu and Boba @ Sweetheart Cafe", "📍 Late Night In-N-Out!"],
            caption: [
                
                """
                Autogenerated costs: ~$40 / person, split across food and transportation.
                """,
                
                """
                Booked for 8 hours ($115, split 5 ways) and left from Stanford University.
                
                Drove 40 mins to SF. Definitely jam out with friends--Miley Cyrus anyone?
                
                Honestly, any music is fine. We just had the windows down, and enjoyed the beautiful scenery. California can't be missed.
                """,
                """
                Hole-in-the-wall hotspot! Ordered salmon poke and rice for under $10. 
                
                ORDER AHEAD! It's such a long wait.
                
                Amogh, when you look back at this, remember all the out-of-pocket things you said. Don't worry, no one else will remember ;)
                """,
                """
                Drove up to a gorgeous viewpoint with all of SF’s lights in view.
                
                Some of the best lights we've ever seen. Thank you SF for the best views <3
                
                San Francisco, you have our hearts. At this moment, we were so so grateful to be here at Stanford.
                """,
                
                """
                A ($11) treat for our sweet tooth. Best bingsu… ever? Chocolate and Strawberry ftw!
                
                Please Lawrence, if you ever look back at this, don't eat all the strawberry BingSu in the future.
                """,
                
                """
                Double-double animal style, please! Burgers for <$5. Totally cheap.
                
                Comfort food of all students here in the Bay Area. 
                """
            ],
            images: ["861A6374", "IMG_5186"]
        )
        
    ),
    
    PostModel(
        title: "Our Annual ASES Retreat",
        info: "6 photos, 1 video",
        caption: "Good friends, food, and really cold weather!",
        media: ["Chinatown 1", "IMG_8239", "Chinatown 3", "Fish 1", "Fish 2", "IMG_8224", "IMG_0021", "IMG_7749", "DSCN1457"],
        username: "liu.lawrence45",
        profilePicture: "04B0D33D-83BB-4E23-BE56-50EFA4FB1B7C",
        numberOfComments: 10,
        friendsMutuals: [15, 15],
        itinerary: ItineraryModel(
            title: ["Driving to the Venture Retreat Center", "Beach Pit Stop", "Formal Night"],
            caption: [
                """
                We started off with a quick drive to the venture retreat center: https://www.ventureretreat.org
                
                Some info about Venture Retreat:
                       1. Pricing was relatively well-off, around $1k per night for 30+.
                       2. You basically live in huts (if you see on the website). Worth it for the experience.
                       3. There's a pool advertised as well: you won't be able to swim most likely from Oct. - March because of the cold.
                
                The car ride was super fun. The road is extremely windy close to the home though, so be careful!
                """,
                
                """
                We made a quick beach stop at San Gregorio State Beach. We honestly were supposed to get to the retreat center on time,
                but thankfully we stopped.
                
                Truly just something out of a movie.
                
                Future Recs: Definitely stop at any beaches you see.
                """,
                
                """
                fun formal night with all friends and digicams!
                """
            ]
            //checklist: ""
        )
    ),
    

    PostModel(
        title: "bedbunk x10",
        info: "",
        caption: "once in a lifetime experience",
        media: ["DSCN1352", "IMG_6986", "IMG_7536", "IMG_7546", "IMG_7559", "71949328572__F6A582E5-6E06-437D-80E5-9F0A5199AA65"],
        username: "liu.lawrence45",
        profilePicture: "04B0D33D-83BB-4E23-BE56-50EFA4FB1B7C",
        numberOfComments: 6,
        friendsMutuals: [10, 4],
        itinerary: ItineraryModel(
            title: ["dorm rooms in okada", "go to main quad", "late nights at branner?"],
            caption: [
                """
                """,
                """
                """
            ],
            checklist: ""
        )
    ),
    
    PostModel(
        title: "half-moon bay adventure!",
        info: "7 photos",
        caption: "fun w my friends :)",
        media: ["IMG_5136", "IMG_5137", "IMG_5169", "IMG_5171" , "IMG_5186", "IMG_5204"],
        username: "kcheng05",
        profilePicture: "IMG_5155",
        numberOfComments: 2,
        friendsMutuals: [1, 2],
        itinerary: ItineraryModel(
            title: ["stop by trader joes", "visit lake", "half moon bay!"],
            caption: [
                """
                """
            ],
            checklist: ""
        )
    )
    
    

]
